apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp3
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: app-container5
        image: marker03/myapp3:latest  # Ensure this image exists on Docker Hub
        ports:
        - containerPort: 85  # Ensure your app inside the container listens on this port
